<?php

/**
 * @file
 * Contains ccei_indicators.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ccei_indicators_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ccei_indicators module.
    case 'help.page.ccei_indicators':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides an indicators block') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function ccei_indicators_theme() {
  $items['indicators_block'] = [
    'variables' => [
      'title' => NULL,
      'indicators' => [],
      'display_header' => TRUE,
      'content' => NULL,
    ],
    'render element' => 'children',
  ];

  $items['ccei_indicators_details_summary'] = [
    'preprocess functions' => [
      'template_preprocess_ccei_indicators_details_summary',
    ],
    'file' => 'ccei_indicators.theme.inc',
  ];

  return $items;
}
