<?php

/**
 * @file
 * Contains ccei_subject.module..
 */

/**
 * Implements hook_theme().
 */
function ccei_subject_theme() {
  return [
    // Add template for our powerbi formatter.
    'power_bi_formatter' => [
      'variables' => [
        'title' => NULL,
        'url_title' => NULL,
        'url' => NULL,
      ],
      'template' => 'power-bi-formatter',
    ],
    // Add field template for powerbi_data.
    'field__field_powerbi_data' => [
      'template' => 'field--field-powerbi-data',
      'base hook' => 'field',
    ],
    // Add views block template for subject icons.
    'block__views_block__subject_icons_block_1' => [
      'template' => 'block--views-block--subject-icons-block-1',
      'base hook' => 'views',
    ],
    // Add views formatter template for subject icons.
    'views_view_unformatted__subject_icons' => [
      'template' => 'views-view-unformatted--subject_icons',
      'base hook' => 'views_view_unformatted',
    ],
  ];
}
